name:  Gitleaks GitHub Actions 
on: 
  push:
    branches:
      - master
  
jobs:
  Explore-GitHub-Actions: 
    runs-on: [ self-hosted, Linux, X64, sgo-runner ]
    env:
      temp_directory: '/home/ec2-user/JuiceShop/gitleaks-scan-reports'
      file_name: '/secrets_report_${{ github.event.repository.name }}_$(date +"%Y_%m_%dT%H:%M:%S").json'
    steps:
      - run: echo "🔎 The name of your branch is ${GITHUB_REF##*/} and your repository is ${{ github.repository }}."
      - name: Run Gitleaks Scan on the GitHub Repository.
        run: gitleaks --repo-url=https://github.com/${{ github.repository }} -v --access-token=${{ secrets.GIT_TOKEN }} --report=${{ env.temp_directory }}${{ env.file_name }}
        continue-on-error: true
